const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const CONFLICT = 409;
const DEFAULT_ERROR = 500;

const DUPLICATE_KEY_ERROR_CODE = 11000;

const DEFAULT_ERROR_MESSAGE = "An error has occurred on the server.";

module.exports = {
  BAD_REQUEST,
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  CONFLICT,
  DEFAULT_ERROR,
  DUPLICATE_KEY_ERROR_CODE,
  DEFAULT_ERROR_MESSAGE,
};
